# Generated by Django 4.1.2 on 2023-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('Precio', models.IntegerField(verbose_name='Precio')),
                ('Autor', models.CharField(max_length=200, verbose_name='Nombre Autor')),
                ('Titulo_Original', models.CharField(max_length=200, verbose_name='Titulo Original')),
                ('Tecnica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tecnica')),
                ('Anio', models.IntegerField(verbose_name='Año')),
                ('Detalles_obra', models.TextField(blank=True, null=True, verbose_name='Detalle Obra')),
                ('image', models.ImageField(upload_to='Services', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['created'],
            },
        ),
    ]
