# Generated by Django 4.1.2 on 2023-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
