# Generated by Django 4.1.2 on 2023-07-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_obras_aprobada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='aprobada',
        ),
        migrations.AddField(
            model_name='obras',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
