# Generated by Django 4.1.2 on 2023-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='Detalles_obra',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Obra'),
        ),
    ]
