# Generated by Django 4.1.2 on 2023-06-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_obras_detalles_obra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obras',
        ),
    ]
