# Generated by Django 4.1.2 on 2023-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=200, verbose_name='Rut')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('cp', models.IntegerField(blank=True, null=True, verbose_name='Codigo postal')),
                ('admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['created'],
            },
        ),
    ]
