# Generated by Django 4.1.2 on 2023-06-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_customuser_delete_usersregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
