# Generated by Django 4.1.2 on 2023-06-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['created'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='cp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo postal'),
        ),
        migrations.AddField(
            model_name='users',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='users',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='users',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='users',
            name='rut',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rut'),
        ),
    ]
